name: Build & Deploy Go App Runner

on:
  push:
    branches:
      - main

# Prevent multiple deployments from running concurrently
concurrency:
  group: apprunner-deployment
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: us-west-2
      ECR_REPOSITORY: apprunner-demo
      APP_RUNNER_SERVICE_NAME: AppRunnerDemoService
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::703671892588:role/GitHubAppRunnerDeployRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Docker Image
        run: |
          ECR_URI=${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPOSITORY }}
          docker build -t $ECR_URI:${{ env.IMAGE_TAG }} .
          docker push $ECR_URI:${{ env.IMAGE_TAG }}
          echo "ECR_URI=$ECR_URI:${{ env.IMAGE_TAG }}" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: CDK Deploy
        env:
          IMAGE_IDENTIFIER: ${{ env.ECR_URI }}
          COMMIT_SHA: ${{ github.sha }}
        run: |
          npm run cdk deploy -- --require-approval never
